views/landing.ejs

Description
---------
The elements of the main page were not very responsive. 
Changes
----
Adding some margin and padding.

Updating responsive format

---

static/css/custom.css
views/landing.ejs
views/partials/cards.ejs

Description
-----
Fix some style

Fixed style in landing page

---

static/css/custom.css

Description
---
Change the hover color of the button from blue to orange

fix button hover

---

views/landing.ejs

Ajout du lien notion sur les ministères sur le bouton `Découvrir`.

Adding notion link to discover button

---

src/jobs/__tests__/notion.integration.test.js
src/jobs/infrastructure/notionJobsService.js
src/jobs/infrastructure/notionMinistriesService.js
src/jobs/jobs.controller.js
src/schedulers/pepJobsScheduler.js
static/scripts/loadmore.js
views/jobs.ejs
views/partials/jobList.ejs

Le scroll infini c'est sympa mais ça a ses inconvénients comme le fait de plus pouvoir accèder au footer (et en plus il fonctionnait pas encore)
Du coup, j'ai remplacé par un bouton qui ajoute sur demande, plus UX à mon avis.

Replace with load more button

---

static/scripts/crisp.js
views/partials/header.ejs

Permet de chatter depuis le site avec l'équipe.

Ajout de la chat box Crisp

---

static/scripts/matomo.js
views/jobDetail.ejs
views/partials/jobList.ejs

Remonte sur matomo 2 conversions : 
1 - une quand on clique sur le bouton "Lire l'offre d'emploi" depuis le listing des offres.
2 - une quand on clique sur n'importe quel lien ou mailto dans le bloc en bas des annonces (Si vous avez des questions , Pour candidater etc)

feat: add conversion tracking

---

CONTRIBUTING.md

This PR follows #264.
I did not update the line 32.
@ivangabriele can you tell me if this PR is well done since you merged #264?

docs(contributing): replace references to "tell-me" with "metiers-numeriques"

---

api/resolvers/index.ts
api/resolvers/leads.ts
app/molecules/AdminMenu.tsx
app/molecules/Form/TextInput.tsx
app/molecules/Form/index.tsx
app/organisms/NewletterBar.tsx
app/queries/index.ts
app/queries/lead.ts
graphql/leads.graphql
graphql/schema.graphql
pages/admin/leads.tsx
pages/api/graphql.ts
pages/api/lead.ts
pages/index.tsx
public/legacy.css

https://dinum-metiers-num-staging-pr335.osc-fr1.scalingo.io/

feat(website): add homepage newsletter CTA section

---

app/organisms/Footer/index.tsx
pages/_app.tsx
pages/accessibilite.tsx
pages/donnees-personnelles-et-cookies.tsx
pages/emploi/[slug].tsx
pages/emploi/archive/[slug].tsx
pages/emplois.tsx
pages/index.tsx
pages/mentions-legales.tsx
public/legacy.css

- https://www.numerique.gouv.fr/uploads/rgaa/rgaa4-2019-exemple-declaration.pdf
- https://place-emploi-public.gouv.fr/accessibilite/

feat(website): add accessibility page and mention

---

app/queries/institution.ts
graphql/institutions.graphql
pages/admin/institution/[id].tsx
prisma/migrations/20220705123456_add_institution_showcase_sections/migration.sql
prisma/schema.prisma

- Add challenges, mission, structure & organisation text blocks on Institution page BO

feat(admin): add all institution page text blocks

---

app/organisms/JobCard.tsx

| Before | After |
| ----- | ----- |
| <img width="1160" alt="image" src="https://user-images.githubusercontent.com/7555711/179717962-0154a15f-ed15-4af4-ab02-0ae557536312.png">  | <img width="1156" alt="image" src="https://user-images.githubusercontent.com/7555711/179717910-b129f124-42ef-4718-8322-ebae1d7df33b.png"> |

fix(web): fix job card width

---

pages/emploi/[slug].tsx

see [here](https://mattermost.incubateur.net/betagouv/pl/mje3grcwnprcmei8md5r3d3nxy)

fix(web): fix team description wrong access key

---

app/molecules/AdminForm/Editor.tsx
app/organisms/InstitutionHeader.tsx
app/organisms/JobFilterBar/index.tsx
package.json
yarn.lock

[Mattermost thread](https://mattermost.incubateur.net/betagouv/pl/hahh4yobrtypzeeddg95pf4xoe)

fix(admin): fix MarkdownEditor behavior

---

app/molecules/AdminForm/Editor.tsx
app/organisms/JobCard.tsx
pages/institutions/[slug].tsx

Reverts betagouv/metiers-numeriques#543

Revert "fix(build): fix build on missing address on Institution"

---

app/molecules/AdminForm/Editor.tsx
app/organisms/JobCard.tsx
package.json
pages/institutions/[slug].tsx
yarn.lock

Remove `@singularity/core`'s `MarkdownEditor` (based on `slate`) to replace it with `CKEditor`

feat: switch broken markdown editor to a wysiwyg

---

app/atoms/TextInput.tsx
app/molecules/AdminForm/Textarea.tsx
app/molecules/Form/FileUpload.tsx
app/molecules/Form/TextInput.tsx
app/molecules/Form/index.tsx
app/organisms/Header/Toolbar.tsx
app/organisms/Header/index.tsx
app/organisms/Profile/CheckOffers.tsx
app/theme.ts
pages/api/applications/index.ts
pages/api/auth/profile.ts
pages/api/graphql.ts
pages/candidature/[[...jobId]].tsx
pages/emploi/[slug].tsx

feat: new header + ad-hoc application form

---

app/atoms/Message.tsx
app/organisms/CandidatePool/ApplicationActions.tsx
app/organisms/Header/LinkItem.tsx
app/organisms/Header/Toolbar.tsx
app/organisms/Header/UserMenu.tsx
app/organisms/Header/index.tsx
app/organisms/JobApplicationCard.tsx
app/organisms/Profile/ProfileLayout.tsx
middleware.ts
pages/candidature/[[...jobId]].tsx
pages/espace-candidat.tsx
pages/profil.tsx

[Mattermost convo](https://mattermost.incubateur.net/betagouv/pl/47xq4jau87r57dpaomawiocs8c)

feat: Candidate applications page

---

app/organisms/Header/LinkItem.tsx
app/organisms/Header/UserMenu.tsx
app/organisms/JobCard.tsx
app/organisms/Profile/ProfileForm.tsx
pages/connexion.tsx

[Mattermost convo](https://mattermost.incubateur.net/betagouv/pl/w3o47d4z6jfz9gheyf79dyc8sa)

fix: candidate flow fixes

---

scripts/dev/seed.js

[See error](https://dashboard.scalingo.com/apps/osc-fr1/dinum-metiers-num-staging/deploy/7db65fb9-e2f7-4e3e-b3cd-e5a398a4acb7)

fix: handle seed script deletes to avoid fkey constraints

---

package.json
yarn.lock

See https://github.com/microsoft/playwright/issues/15717

fix: update Playwright to fix E2E tests
